@startuml C4-Context-Deposits-MVP
title Открытие депозитов (MVP) Context Diagram
top to bottom direction

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Container.puml

Person(Client, "Клиент банка")
Person_Ext(CallCenterEmployeeExternal, "Сотрудник партнёрского Кол-центра")

System_Ext(SMSGate, "SMS-шлюз")
System_Ext(Telecom, "Телеком оператор")
System_Ext(CallCenterSystemExternal, "Система партнёрского кол-центра")
    
Boundary(StandartSystem, "Банк Стандарт"){ 

    Person(CallCenterEmployee, "Сотрудник Кол-центра")
    Person(DepositeManager, "Менеджер депозитов бэк-офиса")
    Person(CreditManager, "Кредитный менеджер бэк-офиса")
    Person(FrontOficceManager, "Сотрудник фронт-офиса")
    
    System(WebSite, "Сайт банка", "[PHP, React.js]")
    System(CallCenterSystem, "Система кол-центра", "[React.js, Java Spring Boot, PostgreSQL]")
    
    Rel(CallCenterSystemExternal, CallCenterSystem, "Передача заявки на расчёт ставки депозита")
    Rel(CallCenterEmployee, CallCenterSystem, "Регистрация заявки на расчёт ставки депозита")
    Rel(CallCenterEmployeeExternal, CallCenterSystemExternal, "Регистрация заявки на расчёт ставки депозита")

    System(ABSSystem, "АБС","Delphi,Oracle")

    System(InternetBankSystem, "Модифицированный Интернет Банк (MVP)", "DotNet, MS SQL")
}

Rel(Client, InternetBankSystem, "Управление интернет банком","HTTPS")
Rel(InternetBankSystem, ABSSystem, "Управление заявками на депозит","HTTPS")

Rel(DepositeManager, ABSSystem, "Взаимодействие с АБС")
Rel(ABSSystem,DepositeManager,  "")
Rel(CreditManager, ABSSystem, "Взаимодействие с АБС")
Rel(ABSSystem,CreditManager,  "")
Rel(FrontOficceManager, ABSSystem, "Взаимодействие с АБС")
Rel(ABSSystem, FrontOficceManager, "")

Rel(Client, WebSite, "Регистируется, подаёт заявку на депозит")
Rel(WebSite, CallCenterSystem, "Регистирует заявку на депозит")
Rel(CallCenterSystem, InternetBankSystem, "Заявки на депозит")

Rel(InternetBankSystem, SMSGate, "Отправка SMS")
Rel(ABSSystem, SMSGate, "Отправка SMS")
Rel(SMSGate, Telecom, "Отправка SMS")

@enduml
